---
- name: Log into DockerHub
  docker_login:
    username: '{{ app_docker_login }}'
    password: '{{ app_docker_password }}'
    email: '{{ app_docker_email }}'
  when: app_docker_login is not none

- name: Pull application image
  docker_image:
    force: '{{ app_force_image_pull }}'
    name: '{{ app_docker_image }}'
    tag: '{{ app_docker_image_tag }}'
  register: app_docker_image_status
