---
- name: Create app settings directory
  file:
    path: '{{ app_settings_path }}'
    state: 'directory'

- name: Render config directories
  file:
    path: "{{ app_settings_path + '/' + item.value | dirname }}"
    state: 'directory'
    recurse: yes
  with_dict: '{{ app_configuration_files }}'

- name: Render config files
  copy:
    src: "{{ app_files_local_folder }}/{{ item.key }}"
    dest: '{{ app_settings_path }}/{{ item.value }}'
  with_dict: '{{ app_configuration_files }}'
  register: app_configs_status

- name: Prepare volumes list
  set_fact:
    app_container_volumes: "{{ app_container_volumes|default([]) + [ app_settings_path + '/' + item.value + ':/app/' + item.value + ':ro' ] }}"
  with_dict: '{{ app_configuration_files }}'
  changed_when: app_configs_status.changed

- name: Prepare empty volumes list
  set_fact:
    app_container_volumes: []
  when: app_container_volumes is not defined
  changed_when: false
