---
- block:
  - name: 'Migrations: run'
    run_once: true
    docker_container:
      name: 'migrations'
      image: '{{ app_tagged_docker_image }}'
      state: started
      detach: false
      command: '{{ app_migration_command }}'
      env: '{{ app_container_environment }}'
      volumes: '{{ app_container_volumes }}'
      log_driver: json-file
    register: app_migrations_status
    changed_when: false

  always:
  - name: 'Migrations: clean'
    docker_container:
      name: 'migrations'
      image: '{{ app_tagged_docker_image }}'
      state: absent
    changed_when: false

  - name: 'Migrations: check status'
    assert:
      msg: Migrations should succeed
      that: app_migrations_status|success
